### ISSUE TITLE
Support for launch template

### ISSUE THREAD

**Issue by nicolasbelanger** [hellofresh/eks-rolling-update#10]
Currently, `eks-rolling-update` only supports `launch configurations`.  Doing a plan (dry-run) over a cluster created with `launch template` instead (using eksctl) will throw this error:

```
 2019-09-06 17:50:31,413 INFO     Describing autoscaling groups...
 2019-09-06 17:50:31,979 INFO     *** Checking autoscaling group eksctl-nicolas-test-cluster-nodegroup-ng-1-NodeGroup-1476EK4LIRYXE ***
 Traceback (most recent call last):
   File "eks_rolling_update.py", line 152, in <module>
     plan_asgs(filtered_asgs)
   File "/app/lib/aws.py", line 248, in plan_asgs
     asg_lc_name = asg['LaunchConfigurationName']
 KeyError: 'LaunchConfigurationName'
```

Any plan on supporting the new and shinny `launch template`  ?  Thanks!

**Comment by crhuber** [comment]
@nicolasbelanger  i will probably look at adding cordon before this one

**Comment by cablespaghetti** [comment]
I've begun work on this and will make a PR when I've tidied things up a bit. @nicolasbelanger are you using Launch Templates within a Mixed Instances Policy?

https://github.com/cablespaghetti/eks-rolling-update/commit/d5a185982043f807cb298f55c33490d198c9f4b0

**Comment by nicolasbelanger** [comment]
@cablespaghetti TBH, My test was fairly simple, single ASG, no `MixedInstancesPolicy`...

**Comment by cablespaghetti** [comment]
Ok. I'll add support for the basic case. Currently I've only taken account of the MixedInstancesPolicy option which is what we use.
