### ISSUE TITLE
kubernetes lib 12.0.0 breaks authentication mechanism#

### ISSUE THREAD

**Issue by mbelang** [hellofresh/eks-rolling-update#72]
Since kubernetes released v 12.0.0 of the python library I have this error:

```
null_resource.eks-rolling-update (local-exec): 2020-10-16 20:17:02,122 INFO     Describing autoscaling groups...
null_resource.eks-rolling-update (local-exec): 2020-10-16 20:17:02,544 INFO     Pausing k8s autoscaler...
null_resource.eks-rolling-update (local-exec): Traceback (most recent call last):
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
null_resource.eks-rolling-update (local-exec):     (self._dns_host, self.port), self.timeout, **extra_kw
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
null_resource.eks-rolling-update (local-exec):     raise err
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
null_resource.eks-rolling-update (local-exec):     sock.connect(sa)
null_resource.eks-rolling-update (local-exec): ConnectionRefusedError: [Errno 111] Connection refused

null_resource.eks-rolling-update (local-exec): During handling of the above exception, another exception occurred:

null_resource.eks-rolling-update (local-exec): Traceback (most recent call last):
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
null_resource.eks-rolling-update (local-exec):     chunked=chunked,
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
null_resource.eks-rolling-update (local-exec):     conn.request(method, url, **httplib_request_kw)
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/http/client.py", line 1244, in request
null_resource.eks-rolling-update (local-exec):     self._send_request(method, url, body, headers, encode_chunked)
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/http/client.py", line 1290, in _send_request
null_resource.eks-rolling-update (local-exec):     self.endheaders(body, encode_chunked=encode_chunked)
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/http/client.py", line 1239, in endheaders
null_resource.eks-rolling-update (local-exec):     self._send_output(message_body, encode_chunked=encode_chunked)
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
null_resource.eks-rolling-update (local-exec):     self.send(msg)
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/http/client.py", line 966, in send
null_resource.eks-rolling-update (local-exec):     self.connect()
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 184, in connect
null_resource.eks-rolling-update (local-exec):     conn = self._new_conn()
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
null_resource.eks-rolling-update (local-exec):     self, "Failed to establish a new connection: %s" % e
null_resource.eks-rolling-update (local-exec): urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc53687a3d0>: Failed to establish a new connection: [Errno 111] Connection refused

null_resource.eks-rolling-update (local-exec): During handling of the above exception, another exception occurred:

null_resource.eks-rolling-update (local-exec): Traceback (most recent call last):
null_resource.eks-rolling-update (local-exec):   File "/usr/local/bin/eks_rolling_update.py", line 8, in <module>
null_resource.eks-rolling-update (local-exec):     sys.exit(main())
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/site-packages/eksrollup/cli.py", line 282, in main
null_resource.eks-rolling-update (local-exec):     modify_k8s_autoscaler("pause")
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/site-packages/eksrollup/lib/k8s.py", line 83, in modify_k8s_autoscaler
null_resource.eks-rolling-update (local-exec):     body
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api/apps_v1_api.py", line 4511, in patch_namespaced_deployment
null_resource.eks-rolling-update (local-exec):     return self.patch_namespaced_deployment_with_http_info(name, namespace, body, **kwargs)  # noqa: E501
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api/apps_v1_api.py", line 4636, in patch_namespaced_deployment_with_http_info
null_resource.eks-rolling-update (local-exec):     collection_formats=collection_formats)
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 353, in call_api
null_resource.eks-rolling-update (local-exec):     _preload_content, _request_timeout, _host)
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 184, in __call_api
null_resource.eks-rolling-update (local-exec):     _request_timeout=_request_timeout)
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 413, in request
null_resource.eks-rolling-update (local-exec):     body=body)
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 300, in PATCH
null_resource.eks-rolling-update (local-exec):     body=body)
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 172, in request
null_resource.eks-rolling-update (local-exec):     headers=headers)
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/site-packages/urllib3/request.py", line 80, in request
null_resource.eks-rolling-update (local-exec):     method, url, fields=fields, headers=headers, **urlopen_kw
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/site-packages/urllib3/request.py", line 171, in request_encode_body
null_resource.eks-rolling-update (local-exec):     return self.urlopen(method, url, **extra_kw)
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 330, in urlopen
null_resource.eks-rolling-update (local-exec):     response = conn.urlopen(method, u.request_uri, **kw)
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 762, in urlopen
null_resource.eks-rolling-update (local-exec):     **response_kw
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 762, in urlopen
null_resource.eks-rolling-update (local-exec):     **response_kw
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 762, in urlopen
null_resource.eks-rolling-update (local-exec):     **response_kw
null_resource.eks-rolling-update (local-exec):   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
null_resource.eks-rolling-update (local-exec):     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
null_resource.eks-rolling-update (local-exec):   F
ile "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
null_resource.eks-rolling-update (local-exec):     raise MaxRetryError(_pool, url, error or ResponseError(cause))
null_resource.eks-rolling-update (local-exec): urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /apis/apps/v1/namespaces/kube-system/deployments/cluster-autoscaler (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc53687a3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

Reverting manually to v 11.0.0 works as expected.

**Comment by chancez** [comment]
Also hit this recently.

**Comment by chancez** [comment]
https://github.com/kubernetes-client/python/issues/1284

**Comment by chadlwilson** [comment]
Thanks for the link @chancez - that was helpful. Have submitted a PR that I believe addresses this. If you have ability to sanity check against my PR branch in your environment; that'd be great.
